/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCalendar: typeof import('./src/components/AppCalendar.vue')['default']
    CalendarHeader: typeof import('./src/components/thecalendar/CalendarHeader.vue')['default']
    CalendarHeaderMobile: typeof import('./src/components/thecalendar/CalendarHeaderMobile.vue')['default']
    CalendarMonthDayItem: typeof import('./src/components/thecalendar/CalendarMonthDayItem.vue')['default']
    CalendarWeekdays: typeof import('./src/components/thecalendar/CalendarWeekdays.vue')['default']
    CalendarWeekdaysMobile: typeof import('./src/components/thecalendar/CalendarWeekdaysMobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCalendar: typeof import('./src/components/thecalendar/TheCalendar.vue')['default']
  }
}
